feat: Add pre-commit config for hooks and checkov.yml file

diff --git a/.github/workflows/terraform-ci.yml b/.github/workflows/terraform-ci.yml
--- a/.github/workflows/terraform-ci.yml
+++ b/.github/workflows/terraform-ci.yml
@@ -112,9 +112,8 @@ jobs:
         run: |
           while read -r module; do
             echo "Running Checkov on modules/$module"
-            checkov --directory "modules/$module" --framework terraform --download-external-modules true || { echo "Checkov failed for $module"; exit 1; }
+            checkov --directory "modules/$module" --framework terraform --download-external-modules true --config-file /modules/.checkov.yml || { echo "Checkov failed for $module"; exit 1; }
           done < changed_modules.txt
-
       - name: Run Terraform Unit Tests
         run: |
           while read -r module; do
