test

diff --git a/.github/workflows/terraform-ci.yml b/.github/workflows/terraform-ci.yml
--- a/.github/workflows/terraform-ci.yml
+++ b/.github/workflows/terraform-ci.yml
@@ -87,12 +87,12 @@ jobs:
             tflint --chdir="modules/$module" -f compact || { echo "TFLint failed for $module"; exit 1; }
           done < changed_modules.txt
 
-      - name: Run Checkov
-        run: |
-          while read -r module; do
-            echo "Running Checkov on modules/$module"
-            checkov --directory "modules/$module" --framework terraform --download-external-modules true || { echo "Checkov failed for $module"; exit 1; }
-          done < changed_modules.txt
+    #   - name: Run Checkov
+    #     run: |
+    #       while read -r module; do
+    #         echo "Running Checkov on modules/$module"
+    #         checkov --directory "modules/$module" --framework terraform --download-external-modules true || { echo "Checkov failed for $module"; exit 1; }
+    #       done < changed_modules.txt
 
       - name: Run Terraform Tests
         run: |
