test

diff --git a/.github/workflows/terraform-ci.yml b/.github/workflows/terraform-ci.yml
--- a/.github/workflows/terraform-ci.yml
+++ b/.github/workflows/terraform-ci.yml
@@ -93,3 +93,10 @@ jobs:
             echo "Running Checkov on modules/$module"
             checkov --directory "modules/$module" --framework terraform --download-external-modules true || { echo "Checkov failed for $module"; exit 1; }
           done < changed_modules.txt
+
+      - name: Run Terraform Tests
+        run: |
+          while read -r module; do
+            echo "Running Terraform tests on modules/$module"
+            terraform test -test-directory "modules/$module/test" || { echo "Terraform tests failed for $module"; exit 1; }
+          done < changed_modules.txt
